// tests/utils/selectors.ts
// Centralized resilient selectors for Betty Blocks app.
// Optimized for your current POM implementation.
// Strategy:
// 1. Prefer data-testid
// 2. Fallback to role/text
// 3. Avoid autogenerated CSS classes

export const S = {
  // ─────────────────────────────────────────────────────────────
  // Navigation
  // ─────────────────────────────────────────────────────────────
  nav: {
    dashboard: '[data-testid="nav-dashboard"], a:has-text("Dashboard")',
    projects: '[data-testid="nav-projects"], a:has-text("Projects")',
    tasks: '[data-testid="nav-tasks"], a:has-text("Tasks")',
  },

  // ─────────────────────────────────────────────────────────────
  // Shared
  // ─────────────────────────────────────────────────────────────
  shared: {
    modal: 'div[role="dialog"][aria-modal="true"]',

    confirmDialog:
      '[data-testid="confirm-dialog"], div[role="dialog"]',

    confirmYes:
      '[data-testid="confirm-yes"], button:has-text("Yes"), button:has-text("Confirm")',

    confirmNo:
      '[data-testid="confirm-no"], button:has-text("No"), button:has-text("Cancel")',

    toast:
      '[role="alert"], [data-testid="toast-message"]',

    loading:
      '[data-testid="loading-spinner"], svg.animate-spin',
  },

  // ─────────────────────────────────────────────────────────────
  // Dashboard
  // ─────────────────────────────────────────────────────────────
  dashboard: {
    // KPI cards
    kpiTotalProjects: 'text=/total projects/i >> ..',
    kpiOpenTasks: 'text=/open tasks/i >> ..',
    kpiOverdueTasks: 'text=/overdue tasks/i >> ..',
    kpiHighPriority: 'text=/high priority/i >> ..',

    // Table
    priorityTable: 'table',

    // IMPORTANT: removed :not(:first-child)
    priorityRow: 'tbody tr',

    // Buttons (fallbacks)
    btnView: 'button:has-text("View")',
    btnClose: 'button:has-text("Close")',
  },

  // ─────────────────────────────────────────────────────────────
  // Projects Page
  // ─────────────────────────────────────────────────────────────
  projects: {
    // ── Page level ─────────────────────────────────────────
    btnNew:
      'button:has-text("New Project"), a:has-text("New Project")',

    table:
      'table',

    rows:
      'tbody tr:not(:first-child)',

    rowHeader:
      'tbody tr:first-child td p',

    rowByName: (name: string) =>
      `tbody tr:has-text("${name}")`,

    // ── Action buttons inside row ───────────────────────────
    btnView:
      'button:has-text("View")',

    btnEdit:
      'button:has-text("Edit")',

    btnClose:
      'button:has-text("Close"), button:has-text("Execute")',

    btnCopy:
      'button:has-text("Copy")',

    btnDelete:
      'button:has-text("Delete")',

    // ── Cells ───────────────────────────────────────────────
    statusCell:
      'td:nth-child(5)',

    ownerCell:
      'td:nth-child(2)',
  },


  // ─────────────────────────────────────────────────────────────
  // Project Detail
  // ─────────────────────────────────────────────────────────────

  projectDetail: {

    detailsCard:
      '[data-testid="project-details-card"], div:has(p:has-text("Project Name"))',

    // Header actions
    btnBack:
      '[data-testid="btn-back-projects"], a:has-text("Back"), a:has-text("Back to Projects")',

    btnEdit:
      '[data-testid="btn-edit-project"], button:has-text("Edit Project")',

    btnClose:
      '[data-testid="btn-close-project"], button:has-text("Close Project")',

    btnAddTask:
      '[data-testid="btn-add-task"], button:has-text("Add Task")',

    // Tasks table
    table:
      '[data-testid="project-tasks-table"], table',

    headerRow:
      'tbody tr:first-child',

    rows:
      'tbody tr:not(:first-child)',

    // Task actions
    btnTaskView:
      '[data-testid="ptask-action-view"], button:has-text("View")',

    btnTaskComplete:
      '[data-testid="ptask-action-complete"], button:has-text("Complete")',

    btnTaskEdit:
      '[data-testid="ptask-action-edit"], button:has-text("Edit")',

    btnTaskDelete:
      '[data-testid="ptask-action-delete"], button:has-text("Delete")',

    // Detail fields
    detailLabel: (label: string) =>
      `p:has-text("${label}")`,

    detailValue: (label: string) =>
      `p:has-text("${label}") >> xpath=following-sibling::p[1]`,
  },

  // ─────────────────────────────────────────────────────────────
  // Tasks Page
  // ─────────────────────────────────────────────────────────────
  tasks: {
    // ─────────────────────────────
    // PAGE LEVEL
    // ─────────────────────────────
    btnNewTask:
      '[data-testid="btn-new-task"], button:has-text("New Task")',

    table:
      '[data-testid="project-tasks-table"], table',

    headerRow:
      'tbody tr:first-child',

    rows:
      'tbody tr:not(:first-child)',

    // Actions (row scoped)
    row: {
      view: '[data-testid="task-action-view"], a:has-text("View")',
      edit: '[data-testid="task-action-edit"], button:has-text("Edit")',
      delete: '[data-testid="task-action-delete"], button:has-text("Delete")',
      complete:
        '[data-testid="task-action-complete"], button:has-text("Complete")',
    },

    // Column helpers (generic)
    cellText: 'td p',
  },

  // ─────────────────────────────────────────────────────────────
  // Task Detail
  // ─────────────────────────────────────────────────────────────
  taskDetail: {
    btnBack: '[data-testid="btn-back-tasks"], a:has-text("Back to Tasks")',

    btnEdit: '[data-testid="btn-edit-task"], button:has-text("Edit")',
    btnComplete: '[data-testid="btn-complete-task"], button:has-text("Complete")',
    btnDelete: '[data-testid="btn-delete-task"], button:has-text("Delete")',

    headerName: 'p:has-text("Task Name") + p',
    headerPriority: 'p:has-text("Priority:") + p',
    headerStatus: 'p:has-text("Status:") + p',

    description: 'p:has-text("Description") + p',

    projectLink: 'div:has(> p:text-is("Project")) a',

    assignedTo: 'div:has(> p:text-is("Assigned To")) div p',
    executionDate: 'div:has(> p:text-is("Execution Date")) div p',
    deadline: 'div:has(> p:text-is("Deadline")) div p',
    createdDate: 'div:has(> p:text-is("Created Date")) div p',

    completedAt: '[data-testid="task-detail-completed-at"], text=Completed At',
  },

  // ─────────────────────────────────────────────────────────────
  // Create/Edit Project Modal
  // ─────────────────────────────────────────────────────────────
  projectModal: {
    container:
      'div[role="dialog"][aria-modal="true"]',

    nameInput:
      '#Name, input[name="Name"]',

    descriptionInput:
      '#Description, textarea',

    statusSelect:
      '#Status, select[name="Status"]',

    deadlineInput:
      '#Deadline, input[type="date"]',

    ownerInput:
      '#Owner, input[name="Owner"]',

    btnCancel:
      'button:has-text("Cancel")',

    btnSubmit:
      'button:has-text("Confirm"), button:has-text("Save"), button:has-text("Create")',

    errorName:
      '[data-testid="error-project-name"], text=/required|minimum|invalid/i',
  },

  // ─────────────────────────────────────────────────────────────
  // Create/Edit Task Modal
  // ─────────────────────────────────────────────────────────────
  taskModal: {
    container:
      'div[role="dialog"][aria-modal="true"]',

    nameInput:
      'input[name="Task Name"], #Task\\ Name',

    descriptionInput:
      'textarea',

    projectSelect:
      'select[name="Project"], #Project',

    assignedInput:
      'select[name="Assigned To"], input[name="Assigned To"]',

    prioritySelect:
      'select[name="Priority"], #Priority',

    statusSelect:
      'select[name="Status"], #Status',

    executionDateInput:
      'input[name="Execution Date"], input[type="date"]',

    deadlineInput:
      'input[name="Deadline"], input[type="date"]',

    btnCancel:
      'button:has-text("Cancel")',

    btnSubmit:
      'button:has-text("Create"), button:has-text("Save"), button:has-text("Confirm")',

    errorName:
      '[data-testid="error-task-name"], text=/required|invalid/i',

    errorProject:
      '[data-testid="error-task-project"], text=/required|invalid/i',
  },

  // ─────────────────────────────────────────────────────────────
  // Auth / OAuth
  // ─────────────────────────────────────────────────────────────
  auth: {
    emailInput:
      'input[name="loginId"], input[type="email"]',

    passwordInput:
      'input[name="password"], input[type="password"]',

    submit:
      'button:has-text("Login"), button:has-text("Next")',
  },


} as const;